#!/usr/bin/env bash
# Writes /etc/nginx/trustgate-cloudflare.conf from Cloudflare's published IP
# ranges. nginx uses it two ways: to accept requests only from Cloudflare's
# edge, and to trust the CF-Connecting-IP header (the real visitor address) only
# when the TCP peer is one of those edges.
#
# The old file is replaced only if the new one is complete, so a failed download
# never leaves nginx without its allow-list.
#
# Overridable for tests: TG_CF_OUT, TG_CF_V4, TG_CF_V6 (URL or file path),
# TG_CF_EXTRA_TRUSTED (TEST ONLY: extra peer addresses to treat as Cloudflare).
set -euo pipefail

OUT=${TG_CF_OUT:-/etc/nginx/trustgate-cloudflare.conf}
V4=${TG_CF_V4:-https://www.cloudflare.com/ips-v4}
V6=${TG_CF_V6:-https://www.cloudflare.com/ips-v6}
EXTRA=${TG_CF_EXTRA_TRUSTED:-}

fetch() { case "$1" in http*) curl -fsS -m 20 "$1" ;; *) cat "$1" ;; esac; }

v4=$(fetch "$V4" | tr -d '\r' | grep -E '^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$' || true)
v6=$(fetch "$V6" | tr -d '\r' | grep -E '^[0-9a-fA-F:]+/[0-9]{1,3}$' || true)

# Sanity: Cloudflare publishes a dozen or so of each. Anything much smaller is a
# failed or truncated download (or an error page), not a real list.
n4=$(printf '%s\n' "$v4" | grep -c . || true); n6=$(printf '%s\n' "$v6" | grep -c . || true)
if [ "$n4" -lt 5 ] || [ "$n6" -lt 3 ]; then
  echo "refusing to update: got $n4 IPv4 and $n6 IPv6 ranges (expected about 14 and 6)" >&2
  exit 1
fi

tmp=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by parent/update-cloudflare-ips.sh on $(date -u +%FT%TZ). Do not edit."
  echo "real_ip_header CF-Connecting-IP;"
  { printf '%s\n' "$v4"; printf '%s\n' "$v6"; for a in $EXTRA; do echo "$a"; done; } | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo '# $tg_from_cloudflare is 1 only when the TCP peer is a Cloudflare edge.'
  echo 'geo $realip_remote_addr $tg_from_cloudflare {'
  echo '    default 0;'
  { printf '%s\n' "$v4"; printf '%s\n' "$v6"; for a in $EXTRA; do echo "$a"; done; } | sed 's/^/    /; s/$/ 1;/'
  echo '}'
} > "$tmp"
chmod 644 "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT ($n4 IPv4 and $n6 IPv6 ranges${EXTRA:+, plus TEST-ONLY extras: $EXTRA})"
